from typing import BinaryIO, Protocol


class StorageBackend(Protocol):
    async def save(self, path: str, data: BinaryIO) -> str: ...
    async def read(self, path: str) -> bytes: ...
    async def delete(self, path: str) -> None: ...
    async def exists(self, path: str) -> bool: ...
    def get_url(self, path: str) -> str: ...
